Retry creating a dmg up to 3 times when it fails.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -105,7 +105,7 @@ resolve() {
             cd ../..
             rm -rf yaml-cpp-0.5.1*
         fi
-        
+
         # node
         if [ ! -d plugin_runner/bin ]; then
             cp -r "C:\Program Files\nodejs" plugin_runner
@@ -143,7 +143,19 @@ build() {
         ensure_dir dmg
         cp -r SilkEdit.app dmg
         ln -s /Applications dmg/Applications
-        hdiutil create -volname SilkEdit -srcfolder dmg -ov -format UDZO SilkEdit.dmg
+				n=0
+				MAX=3
+				until [ $n -ge $MAX ]
+				do
+          hdiutil create -volname SilkEdit -srcfolder dmg -ov -format UDZO SilkEdit.dmg && break
+          echo "Failed to create DMG. retrying"
+					n=$[$n+1]
+					sleep 3
+				done
+				if [ $n == $MAX ]; then
+          echo "Failed to create DMG $MAX times"
+					exit 1
+				fi
     elif [ $OS == 'Linux' ]; then
       OS = 'Linux'
     else
@@ -174,7 +186,7 @@ rebuild() {
 analyze() {
     if [ $OS == 'Win32' ]; then
         echo "gcc is used on Windows so clang-check doesn't work"
-        exit
+        exit 1
     fi
 
 	tmpFile=/tmp/clang-check-err
