Improve Windows installer.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -362,6 +362,30 @@ build() {
 }
 
 make_installer() {
+    declare -i argc=0
+    declare -a argv=()
+
+    while (( $# > 0 ))
+    do
+        case "$1" in
+            -*)
+                if [[ "$1" =~ 'edge' ]]; then
+                    EDGE=true
+                    echo 'installer for edge build'
+                fi
+                if [[ "$1" =~ 'sign' ]]; then
+                    SIGN=true
+                fi
+                shift
+                ;;
+            *)
+                ((++argc))
+                argv=("${argv[@]}" "$1")
+                shift
+                ;;
+        esac
+    done
+  
     if [ ! -d build ]; then
       build
     fi
@@ -373,9 +397,16 @@ make_installer() {
         ensure_dir dmg
         cp -R SilkEdit.app dmg
         macdeployqt dmg/SilkEdit.app
-				if [ "$1" = '--sign' ]; then
-          codesign --force --verify --verbose --deep dmg/SilkEdit.app --sign "$2"
-				fi
+        
+        if [ "$SIGN" = true ];then
+          if [ ${#argv[@]} = 1 ];then
+            codesign --force --verify --verbose --deep dmg/SilkEdit.app --sign ${argv[0]}
+          else
+            echo 'error: no key specified'
+            exit 1
+          fi
+        fi
+
         ln -s /Applications dmg/Applications
 				n=0
 				MAX=3
@@ -414,15 +445,24 @@ make_installer() {
         attrib -r $RELEASE_DIR/vcruntime140.dll
         cd $RELEASE_DIR
 
+        ISS_FILE=../../innoSetup/modified_silkedit.iss
+        if [ "$EDGE" = true ];then
+          # set an app icon for edge build and change AppName
+          cat ../../innoSetup/silkedit.iss | sed -e 's/app_icon_39x41.bmp/app_icon_edge_39x41.bmp/' | sed -e 's/#define MyAppName "SilkEdit"/#define MyAppName "SilkEdit Edge"/' > ${ISS_FILE}
+        else
+          cp ../../innoSetup/silkedit.iss ${ISS_FILE}        
+        fi
+
         if [ $OS = 'Win32' ]; then
           X86_ISS=../../innoSetup/silkedit_x86.iss
           # Change Arch to x86 and remove ArchitecturesAllowed=x64 for x86 installer
-          cat ../../innoSetup/silkedit.iss | sed -e 's/#define Arch "x64"/#define Arch "x86"/' | grep -v ArchitecturesAllowed=x64 > ${X86_ISS}
-          iscc ${X86_ISS}
-          rm ${X86_ISS}
+          cat ${ISS_FILE} | sed -e 's/#define Arch "x64"/#define Arch "x86"/' | grep -v ArchitecturesAllowed=x64 > ${ISS_FILE}
+          iscc ${ISS_FILE}
         else
-            iscc ../../innoSetup/silkedit.iss
+          iscc ${ISS_FILE}
         fi
+        
+        rm ${ISS_FILE}
     fi
 
     cd ..
@@ -592,7 +632,7 @@ case "$1" in
         echo
         ;;
     make_installer)
-        make_installer $2 $3
+        make_installer "$@"
         echo
         ;;
     send_symbol)
